"""SQLAlchemy ORM models for persisting trades, positions, signals, and performance."""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Trade(Base):
    """A single filled order (one side of a round-trip)."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    order_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    symbol: Mapped[str] = mapped_column(String(16), index=True)
    strategy_id: Mapped[str] = mapped_column(String(64), index=True)
    side: Mapped[str] = mapped_column(String(8))           # buy | sell
    quantity: Mapped[int] = mapped_column(Integer)
    fill_price: Mapped[Decimal] = mapped_column(Numeric(12, 4))
    commission: Mapped[Decimal] = mapped_column(Numeric(10, 4), default=Decimal("0"))
    is_options: Mapped[bool] = mapped_column(Boolean, default=False)
    option_contract_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    option_type: Mapped[str | None] = mapped_column(String(4), nullable=True)   # call | put
    strike: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    expiry: Mapped[str | None] = mapped_column(String(16), nullable=True)       # YYYY-MM-DD
    filled_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    wheel_cycle_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("wheel_cycles.id"), nullable=True
    )
    wheel_cycle: Mapped["WheelCycle | None"] = relationship(back_populates="trades")


class Position(Base):
    """Current open position snapshot (overwritten on each sync)."""

    __tablename__ = "positions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(16), unique=True, index=True)
    quantity: Mapped[int] = mapped_column(Integer)
    avg_entry_price: Mapped[Decimal] = mapped_column(Numeric(12, 4))
    current_price: Mapped[Decimal] = mapped_column(Numeric(12, 4))
    unrealized_pnl: Mapped[Decimal] = mapped_column(Numeric(12, 4))
    is_options: Mapped[bool] = mapped_column(Boolean, default=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime)


class Signal(Base):
    """Every signal generated by a strategy (approved or rejected)."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    strategy_id: Mapped[str] = mapped_column(String(64), index=True)
    symbol: Mapped[str] = mapped_column(String(16), index=True)
    signal_type: Mapped[str] = mapped_column(String(32))
    strength: Mapped[float] = mapped_column(Float)
    approved: Mapped[bool] = mapped_column(Boolean)
    rejection_reason: Mapped[str | None] = mapped_column(String(256), nullable=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime, index=True)
    metadata_json: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON blob


class WheelCycle(Base):
    """Tracks one complete Wheel cycle: CSP → (assignment) → CC → close."""

    __tablename__ = "wheel_cycles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(16), index=True)
    state: Mapped[str] = mapped_column(String(32))    # scanning | csp_open | assigned | cc_open
    csp_strike: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    csp_expiry: Mapped[str | None] = mapped_column(String(16), nullable=True)
    csp_premium: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    cc_strike: Mapped[Decimal | None] = mapped_column(Numeric(10, 2), nullable=True)
    cc_expiry: Mapped[str | None] = mapped_column(String(16), nullable=True)
    cc_premium: Mapped[Decimal | None] = mapped_column(Numeric(10, 4), nullable=True)
    stock_cost_basis: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    total_premium_collected: Mapped[Decimal] = mapped_column(Numeric(12, 4), default=Decimal("0"))
    realized_pnl: Mapped[Decimal | None] = mapped_column(Numeric(12, 4), nullable=True)
    completed: Mapped[bool] = mapped_column(Boolean, default=False)
    started_at: Mapped[datetime] = mapped_column(DateTime)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    trades: Mapped[list[Trade]] = relationship(back_populates="wheel_cycle")


class PortfolioSnapshot(Base):
    """End-of-day portfolio snapshot for performance tracking."""

    __tablename__ = "portfolio_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    snapshot_date: Mapped[str] = mapped_column(String(16), index=True)   # YYYY-MM-DD
    cash: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    equity: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    total_value: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    daily_pnl: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    cumulative_pnl: Mapped[Decimal] = mapped_column(Numeric(14, 4))
    open_positions: Mapped[int] = mapped_column(Integer)
    recorded_at: Mapped[datetime] = mapped_column(DateTime)


class WatchlistCandidate(Base):
    """Daily Wheel candidate from automated screener scan."""

    __tablename__ = "watchlist_candidates"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    symbol: Mapped[str] = mapped_column(String(16), index=True)
    scan_date: Mapped[str] = mapped_column(String(16), index=True)   # YYYY-MM-DD
    price: Mapped[float] = mapped_column(Float)
    iv_proxy: Mapped[float] = mapped_column(Float)                    # Finviz volatility %
    options_volume: Mapped[int] = mapped_column(Integer)
    quiverquant_score: Mapped[float] = mapped_column(Float, default=0.0)
    final_score: Mapped[float] = mapped_column(Float)
    source: Mapped[str] = mapped_column(String(32), default="finviz")
    active: Mapped[bool] = mapped_column(Boolean, default=True)
    added_at: Mapped[datetime] = mapped_column(DateTime)
